### ISSUE TITLE
Dataset for Bayesian Hierarchical Model for Change Point Detection in Multivariate Sequences

### ISSUE THREAD

**Issue by AnandShegde** [JINhuaqing/jinhuaqing.github.io#1]
Hello, I am Anand, 3rd year undergraduate at the Indian Institute of technology. I wanted to try out my change point detection method on the wind turbine data that you have used. 
The link that you gave in the paper,  http://www.caict.ac.cn/kxyj/qwfb/bps/201804/t20180426158519.htm is not working. 

Also I am not able to find the Rcode and the data that you have mentioned here.
![image](https://user-images.githubusercontent.com/79975787/198217171-6c3b45f7-abd5-4f5a-84b6-0f0bf9a052d9.png)

Can you please share the dataset?

**Comment by JINhuaqing** [comment]
Hi Anand, plz provide your email. I can send the datasets to you.

**Comment by AnandShegde** [comment]
Thank you for your kind response.
Here is my email ID - anandishegde@gmail.com
